### PR TITLE
re-ordering decklist + full sideboard integration

### PR DESCRIPTION
**Pull request by poppu-mtg**
(1) re-ordering decklist to put lands last for both ASCII and XML  
(2) full sideboard integration for both ASCII and XML (sideboard gets re-ordered too)

### CODE REVIEW

**Comment by silasary** [comment]
Fixes #11?

**Comment by poppu-mtg** [comment]
yes - sorry about your changes, I pulled #11 hoping you would look at it before I merge it...

**Comment by silasary** [comment]
Yeah, it looks alright.  (And doesn't conflict with what I was doing)

**Comment by poppu-mtg** [comment]
I actually added sideboard treatment incl. for the reordering too (doSideMark, doitFirstSB, doitLastSB), so there is a few more lines missing now. The code now checks for an additional sys.argv that would indicate whether the user wants to include the sideboard in the picture.

**Pull request merged**
