### PR TITLE
Better Symbols. 

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Comment by silasary** [comment]
I'm not sure whether these are actually better or not.  It doesn't appear to make much of a difference.

**Comment by silasary** [comment]
With the new symbols:
output

**Comment by poppu-mtg** [comment]
Yes, it looks cleaner - let's use these for now!

**Comment by poppu-mtg** [comment]
just checked the new symbols after having downloaded them, their resolution is vastly improved from what we had so far

**Pull request merged**
