### PR TITLE
Abspath

### LINKED ISSUE #10: running as a cross-platform stand-alone?
is it even possible? I have looked into Nuitka, but not sure this is the best tool out there?

### PR DESCRIPTION
**Pull request by silasary**
Fixes a bunch of issues brought up in the discussion of #32 

We're now able to properly compile EXEs.
Fixes #10

### CODE REVIEW

**Comment by silasary** [comment]
Hmm. Build is failing.  Don't merge this yet.

**Comment by silasary** [comment]
And we're good.

**Comment by JeffHoogland** [comment]
Where are the compiled zips getting posted to? I don't see them on the repo page.

**Comment by silasary** [comment]
They'll be in the releases section. (https://github.com/poppu-mtg/StackIt/releases/)

I'm uploading it now.

**Pull request merged**
