### PR TITLE
Clean up code to support compilation to an exe

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Comment by silasary** [comment]
I managed to compile an exe:
[StackIt.zip](https://github.com/poppu-mtg/StackIt/files/870785/StackIt.zip)

**Comment by JeffHoogland** [comment]
Few issues running this on my Windows 7 test machine:

It is looking for "HexLists" directory in the same directory as as the StackIt.exe

The application is not creating the "Scans" directory.

Moving the HexLists directory and manually creating the Scans directory allow it to work as expected.

**Comment by silasary** [comment]
Yeah, I've noticed this, and am already working on a fix.

**Comment by JeffHoogland** [comment]
Awesome - before you rebuild it is it possible to also make the default font for Hex deck be Arial Bold.ttf with 16 / 18 point font?

**Comment by silasary** [comment]
Is that for the Title Font, or card font, or both?

**Comment by JeffHoogland** [comment]
Same font for both. 18 pt font for title, 16 for card.

**Comment by silasary** [comment]
How does this look?

output

**Comment by JeffHoogland** [comment]
Fantastic.

**Comment by poppu-mtg** [comment]
I was just thinking: can we shift the starting position for the deck title in Hex so that it starts after the champion column? That would be quicker than adding a "champ/nochamp" flag at the prompt

**Comment by JeffHoogland** [comment]
Yea - that sounds like a great idea actually.

**Comment by silasary** [comment]
Maybe.  Is it possible for a Hex deck to *not* have a champion?

Also, I was curious, and decided to test it with Beleran (Ariel Bold feels a bit too bland for me.) 
How does this one look?

output

**Comment by JeffHoogland** [comment]
Decks will always have champions. 

That font does look better, but it is harder to read on smaller screens. Would rather just have the most readable font.

**Comment by silasary** [comment]
Fair enough.  I'll probably end up adding a setting at some point.  For now, I'll just leave it on Ariel.  It is a vast improvement from the previous font.

**Pull request merged**
