### PR TITLE
[RFC] Higher image quality in output

### PR DESCRIPTION
**Pull request by bakert**
I'm nearly there with this one but not quite. Looking for a solution to the problem below ...

Use a 'quality multiplier' to make a bigger image for higher quality output.

Unfortunately the final downsampling in

    if QUALITY_MULTIPLIER != 1:
         width, height = deck.size
         deck = deck.resize((int(width / QUALITY_MULTIPLIER), int(height / QUALITY_MULTIPLIER)), FILTER)

is not very successful and hides most of the (great) improvement.

Trying to find a better solution for that part - Chrome and Preview (for
example) are able to show the image beautifully at the standard 270px width.

Photoshop and pillow seem to have issues.

### CODE REVIEW

**Comment by bakert** [comment]
Image at QUALITY_MULTIPLIER = 4 with no resize at the end:

captura de pantalla 2017-07-23 a las 6 15 16 pm

This image looks great even when constrained to 270px width in Preview or Chrome.

Image after I let pillow do the final resizing (Photoshop is similar with various modes tried):

captura de pantalla 2017-07-23 a las 6 14 32 pm

Original quality of StackIt before my changes:

captura de pantalla 2017-07-23 a las 6 21 05 pm

It's probably mergeable as-is to get the improvements but I'd love to find a fix to go a step further.

**Comment by silasary** [comment]
I'll look at this properly after I get a bit more sleep.

Can I get you to check that the outputs for Pokemon and Hex still look good?  (There are relevant lists in the testdecks folder)

**Comment by silasary** [comment]
Fix up the merge conflicts, and I'll merge it in

**Comment by bakert** [comment]
I fixed the merge conflicts here but the new refactor to put most of the code in the StackIt subdir means I can't run it to check. I think we need to rename StackIt.py (to run.py or similar?)

This should be fine to merge as I get the error running `python StackIt.py` on master too.

**Comment by bakert** [comment]
This is good to merge. I can test it locally now. It won't work without #76 unless you have all the images in cache, but nothing will :)

**Pull request merged**
